### ISSUE TITLE
Setup EC2/Infrastructure + Laravel Base Installation 

### ISSUE THREAD

**Issue by xdmtk** [ArteenGalstyan/Oviatt-Research-Assistant#1]
Infrastructure
---
* Setup EC2 instance
* Setup domain name/name servers
* Setup user accounts + virtual hosts/subdomains 
* Setup SSH access
* Setup MySQL

Code & Devops 
---
* Setup Laravel base installation for all users
* Setup production and develop Laravel environments
* Create `.env` files 
* Create rough CI scripts for prod/dev auto deployment

**Comment by xdmtk** [comment]
Going to break 
>Create rough CI scripts for prod/dev auto deployment

into a separate ticket

**Comment by Vel4ta** [comment]
thank you
